package copytext

// Required keys and placeholders bind editable copy to gameplay.
var required = map[string][]string{
	"ui.help_guide.start":           {},
	"ui.help_guide.controls":        {},
	"ui.help_guide.counters":        {},
	"ui.help_guide.specialists":     {},
	"ui.help_guide.lair":            {},
	"ui.help_guide.topic":           {},
	"ui.help_guide.scroll":          {},
	"ui.help_guide.position":        {"first", "last", "lines", "page", "pages"},
	"ui.help_guide.goal_title":      {},
	"ui.help_guide.goal":            {},
	"ui.help_guide.opening_title":   {},
	"ui.help_guide.opening":         {},
	"ui.help_guide.modes_title":     {},
	"ui.help_guide.modes":           {},
	"ui.help_guide.saves_title":     {},
	"ui.help_guide.saves":           {},
	"ui.help_guide.placement_title": {},
	"ui.help_guide.manage_title":    {},
	"ui.help_guide.pace_title":      {},
	"ui.help_guide.other_title":     {},
	"ui.help_guide.placement_tip":   {},
	"ui.help_guide.manage_tip":      {},
	"ui.help_guide.pace_tip":        {},
	"ui.help_guide.other_tip":       {},
	"ui.help_guide.rogue_title":     {},
	"ui.help_guide.rogue":           {},
	"ui.help_guide.paladin_title":   {},
	"ui.help_guide.paladin":         {},
	"ui.help_guide.centurion_title": {},
	"ui.help_guide.centurion":       {},
	"ui.help_guide.others_title":    {},
	"ui.help_guide.others":          {},
	"ui.help_guide.forge_title":     {},
	"ui.help_guide.forge":           {},
	"ui.help_guide.ogre_title":      {},
	"ui.help_guide.ogre":            {},
	"ui.help_guide.sapper_title":    {},
	"ui.help_guide.sapper":          {},
	"ui.help_guide.witch_title":     {},
	"ui.help_guide.witch":           {},
	"ui.help_guide.limit":           {},
	"ui.help_guide.route_title":     {},
	"ui.help_guide.route":           {},
	"ui.help_guide.relic_title":     {},
	"ui.help_guide.relic":           {},
	"ui.help_guide.seed_title":      {},
	"ui.help_guide.seed":            {},
	"ui.help_guide.replay_title":    {},
	"ui.help_guide.replay":          {},

	"ui.save.failed":       {},
	"ui.save.quit_warning": {},
	"overworld.ow_spend_relic.gunner_already_reserved":                            {},
	"defenders.runeforge.name":                                                    {},
	"defenders.runeforge.subtitle":                                                {},
	"defenders.runeforge.lore":                                                    {},
	"defenders.runeforge.note":                                                    {},
	"defenders.hookmaster.name":                                                   {},
	"defenders.hookmaster.subtitle":                                               {},
	"defenders.hookmaster.lore":                                                   {},
	"defenders.hookmaster.note":                                                   {},
	"defenders.sappers.name":                                                      {},
	"defenders.sappers.subtitle":                                                  {},
	"defenders.sappers.lore":                                                      {},
	"defenders.sappers.note":                                                      {},
	"defenders.witch.name":                                                        {},
	"defenders.witch.subtitle":                                                    {},
	"defenders.witch.lore":                                                        {},
	"defenders.witch.note":                                                        {},
	"ui.training.next_defense":                                                    {},
	"ui.training.after_wave":                                                      {"wave"},
	"ui.keyboard.place":                                                           {},
	"ui.keyboard.rotate":                                                          {},
	"ui.keyboard.upgrade":                                                         {"gold"},
	"ui.keyboard.need":                                                            {"gold"},
	"ui.keyboard.max":                                                             {},
	"ui.keyboard.target":                                                          {"mode"},
	"ui.keyboard.aim":                                                             {"direction"},
	"ui.keyboard.stock":                                                           {"count"},
	"ui.keyboard.sell":                                                            {"gold"},
	"ui.keyboard.next":                                                            {},
	"ui.keyboard.first":                                                           {},
	"ui.keyboard.strongest":                                                       {},
	"ui.keyboard.closest":                                                         {},
	"ui.keyboard.select_defender":                                                 {},
	"ui.keyboard.automatic_mines":                                                 {},
	"ui.keyboard.tab":                                                             {},
	"ui.training.title":                                                           {},
	"ui.tower_info.stats":                                                         {"damage", "level", "range", "tower"},
	"ui.training.continue":                                                        {},
	"ui.training.safe":                                                            {},
	"ui.training.starting_gold":                                                   {},
	"ui.training.funding":                                                         {"gold"},
	"ui.training.plan":                                                            {},
	"ui.training.locked":                                                          {},
	"ui.training.gunner":                                                          {},
	"ui.training.frost":                                                           {},
	"ui.training.cannon":                                                          {},
	"ui.training.ranger":                                                          {},
	"ui.training.slingers":                                                        {},
	"ui.training.lightning":                                                       {},
	"ui.training.trebuchet":                                                       {},
	"ui.training.runeforge":                                                       {},
	"ui.training.hookmaster":                                                      {},
	"ui.training.sappers":                                                         {},
	"ui.training.witch":                                                           {},
	"ui.specialists.placed":                                                       {},
	"ui.specialists.one_per_level":                                                {},
	"ui.specialists.roster_hint":                                                  {},
	"ui.specialists.rotate_hint":                                                  {},
	"ui.specialists.roster_page":                                                  {"page"},
	"ui.specialists.aim_changed":                                                  {"direction"},
	"ui.specialists.aim_prompt":                                                   {},
	"ui.specialists.forge_info":                                                   {"damage", "level", "range", "tower"},
	"ui.specialists.hook_info":                                                    {"level", "pull", "tower"},
	"ui.specialists.sapper_info":                                                  {"cap", "damage", "level", "tower"},
	"ui.specialists.witch_info":                                                   {"bonus", "level", "tower"},
	"afterward.wins_1.lore":                                                       {},
	"afterward.wins_1.title":                                                      {},
	"afterward.wins_10.lore":                                                      {},
	"afterward.wins_10.title":                                                     {},
	"afterward.wins_3.lore":                                                       {},
	"afterward.wins_3.title":                                                      {},
	"afterward.wins_5.lore":                                                       {},
	"afterward.wins_5.title":                                                      {},
	"branding.draw_boot_ui.termtd":                                                {},
	"branding.draw_title_battle_intro.idle_screen":                                {},
	"branding.draw_title_battle_intro.wave_1":                                     {},
	"branding.draw_title_best.best":                                               {"best", "name"},
	"branding.draw_title_best.no_scores_yet":                                      {},
	"branding.draw_title_demo.breach":                                             {},
	"branding.draw_title_demo.idle_screen":                                        {},
	"branding.draw_title_demo.wave_1":                                             {},
	"branding.draw_title_demo.wave_2":                                             {},
	"branding.draw_title_demo.wave_3":                                             {},
	"branding.draw_title_reboot.termtd":                                           {},
	"branding.draw_title_roster.enemies":                                          {},
	"branding.draw_title_roster.towers":                                           {},
	"branding.render_credits.0xbenc":                                              {},
	"branding.render_credits.a_game_by":                                           {},
	"branding.render_credits.back":                                                {},
	"branding.render_credits.created_by":                                          {},
	"branding.render_credits.credits":                                             {},
	"branding.render_credits.kairuku_studios":                                     {},
	"branding.render_credits.off_court_creations":                                 {},
	"branding.render_credits.published_by":                                        {},
	"branding.render_credits.termtd":                                              {},
	"branding.title_screen_box.termtd":                                            {},
	"branding.title_sig.by_kairuku_studios":                                       {},
	"branding.title_tagline.terminal_tower_defense":                               {},
	"characters.cannonier.cannonier":                                              {},
	"characters.cannonier.enlarge_to_view_the_crew":                               {},
	"characters.cannonier.esc_return_tab_portraits":                               {"escape", "tab"},
	"characters.cannonier.one_more_for_the_guild":                                 {},
	"characters.cannonier.tab_ranger_esc_return_q_quit":                           {"escape", "quit", "tab"},
	"characters.centurion.centurion":                                              {},
	"characters.centurion.enlarge_to_view_the_centurion":                          {},
	"characters.centurion.esc_return_tab_portraits":                               {"escape", "tab"},
	"characters.centurion.hold_the_line":                                          {},
	"characters.centurion.tab_squire_esc_return_q_quit":                           {"escape", "quit", "tab"},
	"characters.dragon.enlarge_to_view_malgrath":                                  {},
	"characters.dragon.esc_enter_return_q_quit":                                   {"enter", "escape", "quit"},
	"characters.dragon.malgrath":                                                  {},
	"characters.dragon.tab_grak":                                                  {"tab"},
	"characters.dragon.the_dying_dragon":                                          {},
	"characters.frost.enlarge_to_view_the_mage":                                   {},
	"characters.frost.esc_return_tab_portraits":                                   {"escape", "tab"},
	"characters.frost.frost_mage":                                                 {},
	"characters.frost.tab_player_esc_return_q_quit":                               {"escape", "quit", "tab"},
	"characters.frost.the_cold_remembers":                                         {},
	"characters.gnoll.enlarge_to_view_the_slingers":                               {},
	"characters.gnoll.esc_return_tab_portraits":                                   {"escape", "tab"},
	"characters.gnoll.gnoll_slingers":                                             {},
	"characters.gnoll.one_winds_one_supplies":                                     {},
	"characters.gnoll.tab_gunner_esc_return_q_quit":                               {"escape", "quit", "tab"},
	"characters.grak.enlarge_to_view_grak":                                        {},
	"characters.grak.esc_return_tab_gnolls":                                       {"escape", "tab"},
	"characters.grak.grak":                                                        {},
	"characters.grak.tab_gnolls_esc_return_q_quit":                                {"escape", "quit", "tab"},
	"characters.grak.the_last_monster":                                            {},
	"characters.gunner.enlarge_to_view_the_gunner":                                {},
	"characters.gunner.esc_return_tab_portraits":                                  {"escape", "tab"},
	"characters.gunner.orc_gunner":                                                {},
	"characters.gunner.steady_hands_hot_iron":                                     {},
	"characters.gunner.tab_frost_esc_return_q_quit":                               {"escape", "quit", "tab"},
	"characters.lightning.enlarge_to_view_lightning_mage":                         {},
	"characters.lightning.esc_return_tab_portraits":                               {"escape", "tab"},
	"characters.lightning.lightning_mage":                                         {},
	"characters.lightning.tab_trebuchet_esc_return_q_quit":                        {"escape", "quit", "tab"},
	"characters.lightning.the_storm_takes_hold":                                   {},
	"characters.mercenary.enlarge_to_view_the_mercenary":                          {},
	"characters.mercenary.esc_return_tab_portraits":                               {"escape", "tab"},
	"characters.mercenary.mercenary":                                              {},
	"characters.mercenary.paid_to_be_here":                                        {},
	"characters.mercenary.tab_wizard_esc_return_q_quit":                           {"escape", "quit", "tab"},
	"characters.necromancer.enlarge_to_view_the_necromancer":                      {},
	"characters.necromancer.esc_return_tab_portraits":                             {"escape", "tab"},
	"characters.necromancer.necromancer":                                          {},
	"characters.necromancer.tab_paladin_esc_return_q_quit":                        {"escape", "quit", "tab"},
	"characters.necromancer.they_rise_when_he_falls":                              {},
	"characters.paladin.enlarge_to_view_the_paladin":                              {},
	"characters.paladin.esc_return_tab_portraits":                                 {"escape", "tab"},
	"characters.paladin.paladin":                                                  {},
	"characters.paladin.tab_rogue_esc_return_q_quit":                              {"escape", "quit", "tab"},
	"characters.paladin.the_line_does_not_yield":                                  {},
	"characters.player.enlarge_to_view_the_player":                                {},
	"characters.player.esc_return_tab_portraits":                                  {"escape", "tab"},
	"characters.player.tab_cannonier_esc_return_q_quit":                           {"escape", "quit", "tab"},
	"characters.player.the_guild_s_champion":                                      {},
	"characters.player.the_player":                                                {},
	"characters.ranger.enlarge_to_view_the_ranger":                                {},
	"characters.ranger.esc_return_tab_portraits":                                  {"escape", "tab"},
	"characters.ranger.one_breath_one_shot":                                       {},
	"characters.ranger.ranger":                                                    {},
	"characters.ranger.tab_lightning_esc_return_q_quit":                           {"escape", "quit", "tab"},
	"characters.rogue.already_behind_you":                                         {},
	"characters.rogue.enlarge_to_view_the_rogue":                                  {},
	"characters.rogue.esc_return_tab_portraits":                                   {"escape", "tab"},
	"characters.rogue.rogue":                                                      {},
	"characters.rogue.tab_mercenary_esc_return_q_quit":                            {"escape", "quit", "tab"},
	"characters.squire.enlarge_to_view_the_squire":                                {},
	"characters.squire.esc_return_tab_portraits":                                  {"escape", "tab"},
	"characters.squire.squire":                                                    {},
	"characters.squire.tab_malgrath_esc_return_q_quit":                            {"escape", "quit", "tab"},
	"characters.squire.the_first_expedition":                                      {},
	"characters.trebuchet.a_little_help_with_gravity":                             {},
	"characters.trebuchet.enlarge_to_view_the_trebuchet":                          {},
	"characters.trebuchet.esc_return_tab_portraits":                               {"escape", "tab"},
	"characters.trebuchet.tab_necromancer_esc_return_q_quit":                      {"escape", "quit", "tab"},
	"characters.trebuchet.trebuchet":                                              {},
	"characters.wizard.enlarge_to_view_the_wizard":                                {},
	"characters.wizard.esc_return_tab_portraits":                                  {"escape", "tab"},
	"characters.wizard.tab_centurion_esc_return_q_quit":                           {"escape", "quit", "tab"},
	"characters.wizard.the_shape_of_a_spell":                                      {},
	"characters.wizard.wizard":                                                    {},
	"defenders.cannonier.lore":                                                    {},
	"defenders.cannonier.name":                                                    {},
	"defenders.cannonier.note":                                                    {},
	"defenders.cannonier.subtitle":                                                {},
	"defenders.frost.lore":                                                        {},
	"defenders.frost.name":                                                        {},
	"defenders.frost.note":                                                        {},
	"defenders.frost.subtitle":                                                    {},
	"defenders.gnolls.lore":                                                       {},
	"defenders.gnolls.name":                                                       {},
	"defenders.gnolls.note":                                                       {},
	"defenders.gnolls.subtitle":                                                   {},
	"defenders.gunner.lore":                                                       {},
	"defenders.gunner.name":                                                       {},
	"defenders.gunner.note":                                                       {},
	"defenders.gunner.subtitle":                                                   {},
	"defenders.lightning.lore":                                                    {},
	"defenders.lightning.name":                                                    {},
	"defenders.lightning.note":                                                    {},
	"defenders.lightning.subtitle":                                                {},
	"defenders.ranger.lore":                                                       {},
	"defenders.ranger.name":                                                       {},
	"defenders.ranger.note":                                                       {},
	"defenders.ranger.subtitle":                                                   {},
	"defenders.trebuchet.lore":                                                    {},
	"defenders.trebuchet.name":                                                    {},
	"defenders.trebuchet.note":                                                    {},
	"defenders.trebuchet.subtitle":                                                {},
	"encounters.tactical_brief.inner_courts_can_cover_the_road_more":              {},
	"encounters.tactical_brief.long_bows_reach_across_the_returning_halls":        {},
	"encounters.tactical_brief.separate_banks_need_separate_defenses":             {},
	"encounters.tactical_brief.slow_the_front_ranks_catch_the_crowd":              {},
	"encounters.tactical_brief.thin_the_outer_ranks_finish_the_survivors":         {},
	"encounters.wave_telegraph.a_necromancer_walks_among_them_they_rise":          {},
	"encounters.wave_telegraph.a_paladin_leads_the_vanguard":                      {},
	"encounters.wave_telegraph.a_swift_raid_loose_arrows_fly_true":                {},
	"encounters.wave_telegraph.centurions_warded_they_shrug_off_your_blows":       {},
	"encounters.wave_telegraph.mercenaries_and_they_hit_harder":                   {},
	"encounters.wave_telegraph.the_final_expedition_two_players_hold_the":         {},
	"encounters.wave_telegraph.the_guild_has_sent_rogues":                         {},
	"encounters.wave_telegraph.the_player_has_set_out_if_they":                    {},
	"encounters.wave_telegraph.the_player_returns_stronger":                       {},
	"encounters.wave_telegraph.wizards_fast_and_frail_but_deadly":                 {},
	"encounters.wave_telegraph_for.a_packed_rogue_raid_slow_the_front":            {},
	"encounters.wave_telegraph_for.a_rogue_rush_let_the_outer_defense":            {},
	"encounters.wave_telegraph_for.a_rushing_front_then_heavy_armor_keep":         {},
	"encounters.wave_telegraph_for.a_spaced_column_long_bows_can_cover":           {},
	"encounters.wave_telegraph_for.a_spaced_rogue_raid_long_bows_can":             {},
	"encounters.wave_telegraph_for.raiding_parties_cross_in_bursts_hold_more":     {},
	"encounters.wave_telegraph_for.rogues_in_bursts_cover_the_crossings_and":      {},
	"encounters.wave_telegraph_for.they_arrive_shoulder_to_shoulder_catch_them":   {},
	"encounters.waves.wave_1.theme":                                               {},
	"encounters.waves.wave_10.theme":                                              {},
	"encounters.waves.wave_11.theme":                                              {},
	"encounters.waves.wave_12.theme":                                              {},
	"encounters.waves.wave_13.theme":                                              {},
	"encounters.waves.wave_14.theme":                                              {},
	"encounters.waves.wave_15.theme":                                              {},
	"encounters.waves.wave_16.theme":                                              {},
	"encounters.waves.wave_17.theme":                                              {},
	"encounters.waves.wave_18.theme":                                              {},
	"encounters.waves.wave_19.theme":                                              {},
	"encounters.waves.wave_2.theme":                                               {},
	"encounters.waves.wave_20.theme":                                              {},
	"encounters.waves.wave_3.theme":                                               {},
	"encounters.waves.wave_4.theme":                                               {},
	"encounters.waves.wave_5.theme":                                               {},
	"encounters.waves.wave_6.theme":                                               {},
	"encounters.waves.wave_7.theme":                                               {},
	"encounters.waves.wave_8.theme":                                               {},
	"encounters.waves.wave_9.theme":                                               {},
	"enemies.centurion.lore":                                                      {},
	"enemies.centurion.name":                                                      {},
	"enemies.centurion.note":                                                      {},
	"enemies.centurion.subtitle":                                                  {},
	"enemies.mercenary.lore":                                                      {},
	"enemies.mercenary.name":                                                      {},
	"enemies.mercenary.note":                                                      {},
	"enemies.mercenary.subtitle":                                                  {},
	"enemies.necromancer.lore":                                                    {},
	"enemies.necromancer.name":                                                    {},
	"enemies.necromancer.note":                                                    {},
	"enemies.necromancer.subtitle":                                                {},
	"enemies.paladin.lore":                                                        {},
	"enemies.paladin.name":                                                        {},
	"enemies.paladin.note":                                                        {},
	"enemies.paladin.subtitle":                                                    {},
	"enemies.player.lore":                                                         {},
	"enemies.player.name":                                                         {},
	"enemies.player.note":                                                         {},
	"enemies.player.subtitle":                                                     {},
	"enemies.rogue.lore":                                                          {},
	"enemies.rogue.name":                                                          {},
	"enemies.rogue.note":                                                          {},
	"enemies.rogue.subtitle":                                                      {},
	"enemies.squire.lore":                                                         {},
	"enemies.squire.name":                                                         {},
	"enemies.squire.note":                                                         {},
	"enemies.squire.subtitle":                                                     {},
	"enemies.wizard.lore":                                                         {},
	"enemies.wizard.name":                                                         {},
	"enemies.wizard.note":                                                         {},
	"enemies.wizard.subtitle":                                                     {},
	"memories.depths.easy.lore":                                                   {},
	"memories.depths.easy.title":                                                  {},
	"memories.depths.hard.lore":                                                   {},
	"memories.depths.hard.title":                                                  {},
	"memories.depths.normal.lore":                                                 {},
	"memories.depths.normal.title":                                                {},
	"memories.garden.easy.lore":                                                   {},
	"memories.garden.easy.title":                                                  {},
	"memories.garden.hard.lore":                                                   {},
	"memories.garden.hard.title":                                                  {},
	"memories.garden.normal.lore":                                                 {},
	"memories.garden.normal.title":                                                {},
	"memories.halls.easy.lore":                                                    {},
	"memories.halls.easy.title":                                                   {},
	"memories.halls.hard.lore":                                                    {},
	"memories.halls.hard.title":                                                   {},
	"memories.halls.normal.lore":                                                  {},
	"memories.halls.normal.title":                                                 {},
	"memories.heart.easy.lore":                                                    {},
	"memories.heart.easy.title":                                                   {},
	"memories.heart.hard.lore":                                                    {},
	"memories.heart.hard.title":                                                   {},
	"memories.heart.normal.lore":                                                  {},
	"memories.heart.normal.title":                                                 {},
	"memories.rift.easy.lore":                                                     {},
	"memories.rift.easy.title":                                                    {},
	"memories.rift.hard.lore":                                                     {},
	"memories.rift.hard.title":                                                    {},
	"memories.rift.normal.lore":                                                   {},
	"memories.rift.normal.title":                                                  {},
	"memories.rotunda.easy.lore":                                                  {},
	"memories.rotunda.easy.title":                                                 {},
	"memories.rotunda.hard.lore":                                                  {},
	"memories.rotunda.hard.title":                                                 {},
	"memories.rotunda.normal.lore":                                                {},
	"memories.rotunda.normal.title":                                               {},
	"outcomes.draw_end_beat.the_lair_falls":                                       {},
	"outcomes.draw_end_beat.the_lair_holds":                                       {},
	"outcomes.draw_game_over.best":                                                {},
	"outcomes.draw_game_over.best_2":                                              {"best_score"},
	"outcomes.draw_game_over.combo":                                               {},
	"outcomes.draw_game_over.defeat":                                              {},
	"outcomes.draw_game_over.kills":                                               {},
	"outcomes.draw_game_over.lair":                                                {},
	"outcomes.draw_game_over.leaks":                                               {},
	"outcomes.draw_game_over.malgrath_has_fallen_the_lair_is_clean":               {},
	"outcomes.draw_game_over.new_best":                                            {"best_score"},
	"outcomes.draw_game_over.quit":                                                {},
	"outcomes.draw_game_over.restart":                                             {},
	"outcomes.draw_game_over.score":                                               {},
	"outcomes.draw_game_over.the_lair_is_held_malgrath_endures":                   {},
	"outcomes.draw_game_over.time":                                                {},
	"outcomes.draw_game_over.towers":                                              {},
	"outcomes.draw_game_over.v_view_ending":                                       {"portrait"},
	"outcomes.draw_game_over.victory":                                             {},
	"outcomes.draw_game_over.wave":                                                {},
	"outcomes.end_verdict.a_flawless_hold_not_one_breach":                         {},
	"outcomes.end_verdict.a_hard_fought_hold_the_lair_feels":                      {},
	"outcomes.end_verdict.a_steady_hold_the_lair_endures":                         {},
	"outcomes.end_verdict.the_lair_fell_early_on_wave":                            {"wave"},
	"outcomes.end_verdict.the_lair_fell_late_on_wave":                             {"wave"},
	"outcomes.end_verdict.the_lair_held_to_wave_so_close":                         {"wave"},
	"overworld.depths_locked_message.depths_sealed_beat_all_floors_and_the":       {},
	"overworld.draw_owchrome_rows.cut_c_clear":                                    {"backspace", "clear"},
	"overworld.draw_owchrome_rows.e_ending":                                       {"ending"},
	"overworld.draw_owchrome_rows.free_gunner":                                    {},
	"overworld.draw_owchrome_rows.g_grak":                                         {"grak"},
	"overworld.draw_owchrome_rows.heart":                                          {},
	"overworld.draw_owchrome_rows.i_opening":                                      {"opening"},
	"overworld.draw_owchrome_rows.next_defense":                                   {},
	"overworld.draw_owchrome_rows.no_seed_enter_rolls_the_uncharted":              {},
	"overworld.draw_owchrome_rows.relics":                                         {},
	"overworld.draw_owchrome_rows.seed":                                           {},
	"overworld.draw_owchrome_rows.t_spend_a_relic":                                {"target"},
	"overworld.draw_owchrome_rows.v_malgrath":                                     {"portrait"},
	"overworld.draw_owlabel.depths":                                               {},
	"overworld.draw_owlabel.long_halls":                                           {},
	"overworld.draw_owlabel.rift":                                                 {},
	"overworld.draw_owlabel.sunken_garden":                                        {},
	"overworld.draw_owlabel.the_heart":                                            {},
	"overworld.draw_owvoice.malgrath_endures":                                     {},
	"overworld.draw_owvoice.malgrath_grak_the_guild_still_hunts":                  {},
	"overworld.draw_owvoice.relics_1_60g_2_free_gunner_3":                         {"escape", "gold", "gold_key", "lives", "lives_key", "tokens", "tower_key"},
	"overworld.draw_owvoice.the_heart_beats_light_runs_the_corridors":             {},
	"overworld.draw_owvoice.the_heart_has_unsealed_the_final_expedition":          {},
	"overworld.draw_owvoice.the_lair_stirs_in_the_dark":                           {},
	"overworld.handle_overworld.the_whole_lair_lit_every_floor_revealed":          {},
	"overworld.malgrath.tier_0.line_1":                                            {},
	"overworld.malgrath.tier_0.line_2":                                            {},
	"overworld.malgrath.tier_1.line_1":                                            {},
	"overworld.malgrath.tier_2.line_1":                                            {},
	"overworld.malgrath.tier_3.line_1":                                            {},
	"overworld.malgrath.tier_4.line_1":                                            {},
	"overworld.overworld_footer.back":                                             {},
	"overworld.overworld_footer.descend":                                          {},
	"overworld.overworld_footer.journal":                                          {},
	"overworld.overworld_footer.renown":                                           {},
	"overworld.overworld_footer.walk":                                             {},
	"overworld.ow_dragon_voice_done.malgrath_they_will_come_again_grak_we":        {},
	"overworld.ow_launch.seed_too_large":                                          {},
	"overworld.ow_launch.unknown_floor":                                           {},
	"overworld.ow_node_line.held_20_20":                                           {},
	"overworld.ow_node_line.the_heart_has_unsealed_enter_to_face":                 {},
	"overworld.ow_set_banner.the_heart_is_held_malgrath_endures":                  {},
	"overworld.ow_spend_relic.an_orc_gunner_will_be_waiting_at":                   {"tower"},
	"overworld.ow_spend_relic.the_heart_steadies_1_to_the_next":                   {"lives"},
	"overworld.ow_spend_relic.the_lair_grants_60_gold_to_the":                     {"gold"},
	"overworld.progress.descending":                                               {"floor"},
	"overworld.progress.opened":                                                   {"floor"},
	"overworld.progress.opening":                                                  {"floor"},
	"overworld.progress.sealed":                                                   {"floor"},
	"overworld.render_overworld.the_lair":                                         {},
	"overworld.render_overworld.the_lair_held":                                    {},
	"overworld.results.broke_at":                                                  {"wave"},
	"overworld.results.held":                                                      {"floor"},
	"overworld.results.lost":                                                      {"floor", "wave"},
	"overworld.results.new_best":                                                  {"score"},
	"overworld.results.with_best":                                                 {"floor", "result", "score"},
	"overworld.results.without_best":                                              {"floor", "result"},
	"overworld.rooms.depths.held":                                                 {},
	"overworld.rooms.depths.lost":                                                 {},
	"overworld.rooms.depths.unheld":                                               {},
	"overworld.rooms.garden.held":                                                 {},
	"overworld.rooms.garden.lost":                                                 {},
	"overworld.rooms.garden.unheld":                                               {},
	"overworld.rooms.halls.held":                                                  {},
	"overworld.rooms.halls.lost":                                                  {},
	"overworld.rooms.halls.unheld":                                                {},
	"overworld.rooms.heart.held":                                                  {},
	"overworld.rooms.heart.lost":                                                  {},
	"overworld.rooms.heart.unheld":                                                {},
	"overworld.rooms.rift.held":                                                   {},
	"overworld.rooms.rift.lost":                                                   {},
	"overworld.rooms.rift.unheld":                                                 {},
	"overworld.rooms.rotunda.held":                                                {},
	"overworld.rooms.rotunda.lost":                                                {},
	"overworld.rooms.rotunda.unheld":                                              {},
	"places.depths.lore":                                                          {},
	"places.depths.map_name":                                                      {},
	"places.depths.name":                                                          {},
	"places.depths.note":                                                          {},
	"places.depths.short_name":                                                    {},
	"places.depths.subtitle":                                                      {},
	"places.garden.ledger_name":                                                   {},
	"places.garden.lore":                                                          {},
	"places.garden.map_name":                                                      {},
	"places.garden.name":                                                          {},
	"places.garden.note":                                                          {},
	"places.garden.short_name":                                                    {},
	"places.garden.subtitle":                                                      {},
	"places.halls.ledger_name":                                                    {},
	"places.halls.lore":                                                           {},
	"places.halls.map_name":                                                       {},
	"places.halls.name":                                                           {},
	"places.halls.note":                                                           {},
	"places.halls.short_name":                                                     {},
	"places.halls.subtitle":                                                       {},
	"places.heart.lore":                                                           {},
	"places.heart.map_name":                                                       {},
	"places.heart.name":                                                           {},
	"places.heart.note":                                                           {},
	"places.heart.short_name":                                                     {},
	"places.heart.subtitle":                                                       {},
	"places.rift.ledger_name":                                                     {},
	"places.rift.lore":                                                            {},
	"places.rift.map_name":                                                        {},
	"places.rift.name":                                                            {},
	"places.rift.note":                                                            {},
	"places.rift.short_name":                                                      {},
	"places.rift.subtitle":                                                        {},
	"places.rotunda.ledger_name":                                                  {},
	"places.rotunda.lore":                                                         {},
	"places.rotunda.map_name":                                                     {},
	"places.rotunda.name":                                                         {},
	"places.rotunda.note":                                                         {},
	"places.rotunda.short_name":                                                   {},
	"places.rotunda.subtitle":                                                     {},
	"ui.build_story_journal_entries.afterward_2":                                  {},
	"ui.build_story_journal_entries.earned_after_victories_in_the_heart_or":       {"wins"},
	"ui.cycle_target.no_tower_here":                                               {},
	"ui.difficulty.easy":                                                          {},
	"ui.difficulty.hard":                                                          {},
	"ui.difficulty.normal":                                                        {},
	"ui.draw_beats.the_player":                                                    {},
	"ui.draw_beats.the_siege_begins":                                              {},
	"ui.draw_beats.wave":                                                          {"wave"},
	"ui.draw_journal_collection.chapter_arrows_browse_enter_read_esc":             {"arrows", "chapters", "enter", "escape"},
	"ui.draw_journal_collection.chapter_enter_read_esc":                           {"chapters", "enter", "escape"},
	"ui.draw_journal_collection.chapters_arrows_browse_enter_read_esc_return":     {"arrows", "chapters", "enter", "escape"},
	"ui.draw_journal_collection.unwritten":                                        {},
	"ui.draw_journal_page.chapter_text_esc":                                       {"chapters", "escape", "scroll"},
	"ui.draw_journal_page.chapters_pages_text_esc_collection":                     {"chapters", "escape", "pages", "scroll"},
	"ui.draw_menu.journal":                                                        {},
	"ui.draw_menu.move":                                                           {},
	"ui.draw_menu.move_2":                                                         {},
	"ui.draw_menu.pause":                                                          {},
	"ui.draw_menu.pause_2":                                                        {},
	"ui.draw_menu.place":                                                          {},
	"ui.draw_menu.place_2":                                                        {},
	"ui.draw_menu.quit":                                                           {},
	"ui.draw_menu.quit_2":                                                         {},
	"ui.draw_menu.resume":                                                         {},
	"ui.draw_menu.sell":                                                           {},
	"ui.draw_menu.sell_2":                                                         {},
	"ui.draw_menu.speed":                                                          {},
	"ui.draw_menu.target":                                                         {},
	"ui.draw_menu.target_2":                                                       {},
	"ui.draw_menu.up":                                                             {},
	"ui.draw_menu.up_2":                                                           {},
	"ui.draw_menu.wave":                                                           {},
	"ui.draw_menu.wave_2":                                                         {},
	"ui.film_title.the_last_monster":                                              {},
	"ui.film_title.the_other_side":                                                {},
	"ui.header_segments.build_a_tower":                                            {},
	"ui.header_segments.next_in_s":                                                {"seconds", "wave"},
	"ui.header_segments.termtd":                                                   {},
	"ui.header_segments.wave":                                                     {"max_waves", "wave"},
	"ui.help.move_controls":                                                       {"arrows", "walk"},
	"ui.help.speed_controls":                                                      {"speed"},
	"ui.journal.afterward_requirement":                                            {"wins"},
	"ui.journal.earned_floor":                                                     {"floor", "renown"},
	"ui.journal.floor_requirement":                                                {"floor", "renown"},
	"ui.journal_chapter.i_the_towers":                                             {},
	"ui.journal_chapter.ii_the_guild":                                             {},
	"ui.journal_chapter.iii_the_lair":                                             {},
	"ui.journal_chapter.iv_story_moments":                                         {},
	"ui.journal_lines.in_the_field":                                               {},
	"ui.journal_lines.remembered":                                                 {},
	"ui.journal_lines.the_way_through":                                            {},
	"ui.journal_requirement.encounter_this_guild_fighter_to_write_its":            {},
	"ui.journal_requirement.place_a_tower_to_write_its_page":                      {},
	"ui.journal_requirement.visit_this_part_of_the_lair_to":                       {},
	"ui.menu_items.credits":                                                       {},
	"ui.menu_items.help":                                                          {},
	"ui.menu_items.high_scores":                                                   {},
	"ui.menu_items.journal":                                                       {},
	"ui.menu_items.quick_play":                                                    {},
	"ui.menu_items.quit":                                                          {},
	"ui.menu_items.reset_progress":                                                {},
	"ui.menu_items.start":                                                         {},
	"ui.place.can_t_build_there":                                                  {},
	"ui.render_cutscene.enlarge_to_62_19_to_view":                                 {},
	"ui.render_cutscene.enter_space_next_previous_esc_skip_q":                     {"advance", "escape", "quit"},
	"ui.render_cutscene.enter_space_return_previous_esc_skip_q":                   {"advance", "escape", "quit"},
	"ui.render_cutscene.enter_space_reveal_previous_esc_skip_q":                   {"advance", "escape", "quit"},
	"ui.render_cutscene.esc_skip_q_quit":                                          {"escape", "quit"},
	"ui.render_cutscene.scene_playing_previous_esc_skip_q_quit":                   {"escape", "quit"},
	"ui.render_help.0_9_on_the_depths_the_lair":                                   {"digits"},
	"ui.render_help.1_7_pick_enter_or_click":                                      {"enter", "towers"},
	"ui.render_help.back":                                                         {},
	"ui.render_help.cancel":                                                       {},
	"ui.render_help.descend":                                                      {},
	"ui.render_help.enter_on_a_floor_the_lair":                                    {"enter"},
	"ui.render_help.films":                                                        {},
	"ui.render_help.grak_s_ledger":                                                {},
	"ui.render_help.how_to_hold_the_lair_against_twenty":                          {},
	"ui.render_help.i_opening_e_ending_rotunda":                                   {"ending", "opening"},
	"ui.render_help.j_lair_or_paused_chapters":                                    {"chapters", "journal"},
	"ui.render_help.journal":                                                      {},
	"ui.render_help.move":                                                         {},
	"ui.render_help.n_early_bonus_gold":                                           {"wave"},
	"ui.render_help.pause":                                                        {},
	"ui.render_help.place":                                                        {},
	"ui.render_help.quit":                                                         {},
	"ui.render_help.renown":                                                       {},
	"ui.render_help.seed":                                                         {},
	"ui.render_help.sell":                                                         {},
	"ui.render_help.speed":                                                        {},
	"ui.render_help.t_game_t_relics_lair":                                         {"target"},
	"ui.render_help.tab_the_lair":                                                 {"tab"},
	"ui.render_help.target":                                                       {},
	"ui.render_help.upgrade":                                                      {},
	"ui.render_help.wave":                                                         {},
	"ui.render_high_scores.back":                                                  {},
	"ui.render_high_scores.high_scores":                                           {},
	"ui.render_high_scores.name":                                                  {},
	"ui.render_high_scores.no_scores_yet":                                         {},
	"ui.render_high_scores.score":                                                 {},
	"ui.render_high_scores.scroll":                                                {},
	"ui.render_journal.discover_entries_in_the_campaign":                          {},
	"ui.render_journal.enlarge_to_read_the_journal":                               {},
	"ui.render_journal.grak_s_journal":                                            {},
	"ui.render_journal.iv_afterward":                                              {},
	"ui.render_level_select.back":                                                 {},
	"ui.render_level_select.preview":                                              {},
	"ui.render_level_select.preview_needs_more_room":                              {},
	"ui.render_level_select.quick_play_high_scores_only":                          {},
	"ui.render_level_select.start":                                                {},
	"ui.render_menu.main_menu":                                                    {},
	"ui.render_menu.move":                                                         {},
	"ui.render_menu.quit":                                                         {},
	"ui.render_menu.select":                                                       {},
	"ui.render_reset_progress.all_progress_has_been_reset":                        {},
	"ui.render_reset_progress.also_clears_journal_discoveries_and_story_progress": {},
	"ui.render_reset_progress.cancel":                                             {},
	"ui.render_reset_progress.clears_floor_progress_relics_and_high_scores":       {},
	"ui.render_reset_progress.could_not_reset_all_progress_try_again":             {},
	"ui.render_reset_progress.main_menu":                                          {},
	"ui.render_reset_progress.move":                                               {},
	"ui.render_reset_progress.reset_all_progress":                                 {},
	"ui.render_reset_progress.reset_progress":                                     {},
	"ui.render_reset_progress.select":                                             {},
	"ui.render_reset_progress.this_cannot_be_undone":                              {},
	"ui.render_reset_progress.your_next_start_begins_a_new_journey":               {},
	"ui.render_too_small.needs_at_least_x_enlarge_the_window":                     {"need_h", "need_w"},
	"ui.render_too_small.paused_resize_to_resume":                                 {},
	"ui.render_too_small.termtd_terminal_too_small":                               {},
	"ui.reset_progress_items.cancel":                                              {},
	"ui.reset_progress_items.reset_all_progress":                                  {},
	"ui.setup.difficulty_label":                                                   {},
	"ui.setup.random_seed":                                                        {},
	"ui.setup.seed_label":                                                         {},
	"ui.start_game.seed_too_large":                                                {},
	"ui.start_wave.the_siege_waits_build_a_tower_to":                              {},
	"ui.status.breach":                                                            {"lives"},
	"ui.status.need_gold":                                                         {"gold"},
	"ui.status.sold":                                                              {"gold"},
	"ui.status.target_changed":                                                    {"target", "tower"},
	"ui.status.upgraded":                                                          {"level", "tower"},
	"ui.status.wave_cleared":                                                      {"gold", "wave"},
	"ui.status.wave_incoming":                                                     {"wave"},
	"ui.step_game.the_player_breached_6":                                          {},
	"ui.targeting.closest":                                                        {},
	"ui.targeting.first":                                                          {},
	"ui.targeting.strongest":                                                      {},
	"ui.title_footer.quit":                                                        {},
	"ui.title_footer.start":                                                       {},
	"ui.upgrade_selected.max_level":                                               {},
}
